#include "strace.h"

const char *err_macro[] = {
  [EPERM]	= "EPERM", 
  [ENOENT]	= "ENOENT",
  [ESRCH]	= "ESRCH",
  [EINTR]	= "EINTR",
  [EIO]		= "EIO",
  [ENXIO]	= "ENXIO", 
  [E2BIG]	= "E2BIG", 
  [ENOEXEC]	= "ENOEXEC",
  [EBADF]	= "EBADF", 
  [ECHILD]	= "ECHILD",
  [EAGAIN]	= "EAGAIN",
  [ENOMEM]	= "ENOMEM",
  [EACCES]	= "EACCES",
  [EFAULT]	= "EFAULT",
  [ENOTBLK]	= "ENOTBLK",
  [EBUSY]	= "EBUSY",
  [EEXIST]	= "EEXIST",
  [EXDEV]	= "EXDEV", 
  [ENODEV]	= "ENODEV",
  [ENOTDIR]	= "ENOTDIR",
  [EISDIR]	= "EISDIR",
  [EINVAL]	= "EINVAL",
  [ENFILE]	= "ENFILE",
  [EMFILE]	= "EMFILE",
  [ENOTTY]	= "ENOTTY",
  [ETXTBSY]	= "ETXTBSY",
  [EFBIG]	= "EFBIG",
  [ENOSPC]	= "ENOSPC",
  [ESPIPE]	= "ESPIPE",
  [EROFS]	= "EROFS",
  [EMLINK]	= "EMLINK",
  [EPIPE]	= "EPIPE",
  [EDOM]	= "EDOM",
  [ERANGE]	= "ERANGE",
};
