#include "strace.h"

const char *signal_macro[] = {
  [1] = "SIGHUP",
  [2] = "SIGINT",
  [3] = "SIGQUIT",
  [4] = "SIGKILL",
  [5] = "SIGTRAP",
  [6] = "SIGABRT",
  [7] = "SIGBUS",
  [8] = "SIGFPE",
  [9] = "SIGKILL",
  [10] = "SIGUSR1",
  [11] = "SIGSEGV",
  [12] = "SIGUSR2",
  [13] = "SIGPIPE",
  [14] = "SIGALRM",
  [15] = "SIGTERM",
  [16] = "SIGSTKFLT",
  [17] = "SIGCHLD",
  [18] = "SIGCONT",
  [19] = "SIGSTOP",
  [20] = "SIGTSTP",
  [21] = "SIGTTIN",
  [22] = "SIGTTOU",
  [23] = "SIGTURG",
  [24] = "SIGXCPU",
  [25] = "SIGXFSZ",
  [26] = "SIGVTALRM",
  [27] = "SIGPROF",
  [28] = "SIGWINCH",
  [29] = "SIGIO",
  [30] = "SIGPOLL",
  [31] = "SIGSYS",
  [32] = "SIGRTMIN",
};
